### ISSUE TITLE
Questions on `Numerov` and `Solver` classes

### ISSUE THREAD

**Issue by AndreaIdini** [AndreaIdini/Schroedinger#60]
**Question 1:**
> Numerov::Numerov(Potential potential, int nbox) : Solver(potential, nbox)
> Al momento inizializza la wavefunction, che in realta' andrebbe inizializzata quando si lancia l'algoritmo di bisezione.
> Dato che numerov quello che fa e' lanciare la bisezione una volta, va bene anche cosi' istanziarlo col costruttore, pero' se si cancella quella parte e si fa un init vuoto va tutto in vacca anche inizializzando dentro la bisezione... perche'?

**Question 1.5:**
wave function should be initialised in `Solver`, because the initialisation is valid for every type of solver. It could be more convenient to initialise it directly in the routine that does the actual solving to avoid propagating errors in asymmetric solvers. E.g. `wave function(border) = 0`, 10^-5 is recognised as solution at first matching with 0; 10^-4 at second iteration matching with 10^-5; 10^-3 matching with 10^-4...etc... Evaluate what's best practice.

**Question 2:**
`Numerov::Numerov(Potential potential,  int nbox)` takes `Potential` as input. But `potential` is already a member of class `Solver`. Is there a reason for it?

**Question 3:**
Can we make more clear or efficient the current implementation of scanning + bisection?
At the moment the solver start scanning from the lowest energy with a certain step, once found conditions for sign changes looks at the bisection solution in the middle of the last step.

**Comment by sykhro** [comment]
`Potential` is quite a big thing being passed by value, if we can't get rid of it we should at least change it to a pass-by-reference

**Comment by GabrielePisciotta** [comment]
**Question 1, question 1.5**: we have discussed a lot about this in these months. I consider this questions answered and solved.

**Question 2**: we initialize a Numerov object that's also a Solver object (remember the hierarchy). To initialize a Solver object you need to set the potential that has to be used, so basically passing the potential as an argument in the Numerov initialization you do this. 

**Question 3**: actually this is an important point. Let's schedule a call in the next week in order to look deeper into this.
